name: Run Tests
on: [pull_request]
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: 🏗 Setup repo
              uses: actions/checkout@v3

            - name: 🏗 Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16.x
                  cache: yarn

            - name: 📦 Install dependencies
              run: yarn install

            - name: 🧪 Test
              run: yarn test
